services:
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - JWT_SECRET=${JWT_SECRET:-skinscan-secret-padrao}
      - JWT_HORAS_EXPIRACAO=${JWT_HORAS_EXPIRACAO:-24}
      - API_KEY_OPENCODE=${API_KEY_OPENCODE}
      - BASE_URL_OPENCODE=${BASE_URL_OPENCODE:-https://opencode.ai/zen/go/v1}
      - CHROMADB_HOST=${CHROMADB_HOST:-localhost}
      - CHROMADB_PORT=${CHROMADB_PORT:-8000}
      - CHROMADB_SSL=${CHROMADB_SSL:-false}

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
