services:
  backend:
    build: ./backend
    container_name: skinscan-backend
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: skinscan-frontend
    restart: unless-stopped
    depends_on:
      - backend
